spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        ## ---------- PRODUCT SERVICE ----------
        ## Public READ APIs
        - id: product-service-read
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
            - Method=GET

        ## Protected WRITE APIs
        - id: product-service-write
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
            - Method=POST,PUT,DELETE,OPTIONS
          filters:
            - name: AuthenticationFilter
            - name: RoleFilter
              args:
                requiredRoles: ROLE_ADMIN,ROLE_EMPLOYEE

server:
  port: 8082

jwt:
  secret: VNEqE5Yp+VzqS+kqzqjW+EbLpRm6cC7jmgc+YhoYxD8=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka