spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        ## ---------- PRODUCT SERVICE ----------
        ## Internal Product for Order
        - id: product-service-internal
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/internal/**
            - Method=GET
          filters:
            - name: AuthenticationFilter
            - name: RoleFilter
              args:
                requiredRoles: ROLE_ADMIN,ROLE_EMPLOYEE
        ## Public READ APIs
        - id: product-service-read
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
            - Method=GET

        ## WRITE (POST, PUT)
        - id: product-service-write
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
            - Method=POST,PUT,OPTIONS
          filters:
            - name: AuthenticationFilter
            - name: RoleFilter
              args:
                requiredRoles: ROLE_ADMIN,ROLE_EMPLOYEE

        ## DELETE (for ADMIN only)
        - id: product-service-delete
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
            - Method=DELETE
          filters:
            - name: AuthenticationFilter
            - name: RoleFilter
              args:
                requiredRoles: ROLE_ADMIN

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: AuthenticationFilter

        - id: order-service-admin
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/admin
          filters:
            - name: AuthenticationFilter
            - name: RoleFilter
              args:
                requiredRoles: ROLE_ADMIN,ROLE_EMPLOYEE



server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_EUREKA_URL}